name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Thank you for opening your issue.  
            We appreciate your contribution and will review it soon.

          pr-message: |
            Thank you for submitting your pull request.  
            We appreciate your effort and will review it shortly.
